[build]
  publish = "public"
  command = "npm run build"

[context.production]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/feed/"
  to = "/feed/feed.xml"
  status = 200


[[plugins]]
  package = "./plugins/webmentions-cache"
